config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"
  resources :posts do
    resources :comments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :picture, PictureUploader
  validates :message, presence: true
  validates :picture, presence: true
  has_many :comments

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable,  :rememberable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def render_not_found(status=:not_found)
    render plain: "#{status.to_s.titleize} :(", status: status
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @post = Post.find_by_id(params[:post_id])
    return render_not_found if @post.blank?

    @post.comments.create(comment_params.merge(user: current_user))
    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def destroy
    @post = Post.find_by_id(params[:id])
    return render_not_found if @post.blank?
    return render_not_found(:forbidden) if @post.user != current_user
    @post.destroy
    redirect_to root_path
  end

  def update
    @post = Post.find_by_id(params[:id])
    return render_not_found if @post.blank?
    return render_not_found(:forbidden) if @post.user != current_user
    @post.update_attributes(post_params)

    if @post.valid?
      redirect_to root_path
    else
      return render :edit, status: :unprocessable_entity
    end
  end

  def new
    @post = Post.new
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find_by_id(params[:id])
    return render_not_found if @post.blank?
  end

  def edit
    @post = Post.find_by_id(params[:id])
    return render_not_found if @post.blank?
    return render_not_found(:forbidden) if @post.user != current_user
  end

  def create
    @post = current_user.posts.create(post_params)
    if @post.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:message, :picture)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phorager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,100,300,600,700' rel='stylesheet' type='text/css'>
  </head>

  <body>

    <div class="top-nav">
      <div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
        <div class="brand float-left">
          Phorager
        </div>
        <div class="add float-right">
          <% if current_user %>
            Signed in as <%= current_user.email %>.
            <%= link_to "New Post", new_post_path %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path %>
            <%= link_to "Sign Up", new_user_registration_path %>
          <% end %>
        </div>
      </div>
      <br class="clear-fix" />
    </div>


    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 card form">
<h2>Edit Post</h2>

<%= simple_form_for @post do |f| %>
  <%= f.input :message %>
  <%= f.input :picture %>
  <%= f.submit 'Update', class: 'my-btn' %>
<% end %>

</div>

app/views/posts/index.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
  <% @posts.each do |post| %>
  <div class="card">
    <div class="handle"><%= post.user.email %></div>
    <%= image_tag post.picture.to_s, class: 'img-fluid' %>
    <p>
      <%= post.message %>
    </p>

    <div class="post-actions float-right">
      <% if current_user && current_user == post.user %>
      <%= link_to 'Edit', edit_post_path(post) %>
      <%= link_to 'Delete', post_path(post), method: :delete, data: {confirm: 'Are you sure you want to delete this post?'} %>

      <% end %>
    </div>
    <br class="clear-fix" />
    <div class="comments">
      <h3>Comments</h3>
        <% post.comments.each do |comment| %>
          <div class="comment">
            <span class="comment_handle">
              <%= comment.user.email %>
            </span>

            <%= comment.message %>
          </div>
        <% end %>
      <h4>Add a comment</h4>
      <%= simple_form_for Comment.new, url: post_comments_path(post) do |f| %>
        <%= f.input :message %>
        <%= f.submit 'Add Comment', class: 'my-btn' %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 card form">

<h1>New Post</h1>

<%= simple_form_for @post do |f| %>
  <%= f.input :picture %>
  <%= f.input :message %>
  <%= f.submit "Post!", class: 'my-btn' %>

<% end %>

</div>

app/views/posts/show.html.erb
<%= @post.inspect %>